/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Access: typeof import('./src/components/Access.vue')['default']
    ApplyForAccess: typeof import('./src/components/ApplyForAccess.vue')['default']
    Community: typeof import('./src/components/Community.vue')['default']
    DefaultLayout: typeof import('./src/components/DefaultLayout.vue')['default']
    Documentation: typeof import('./src/components/Documentation.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElText: typeof import('element-plus/es')['ElText']
    GettingStarted: typeof import('./src/components/GettingStarted.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunningOnRISCV: typeof import('./src/components/RunningOnRISCV.vue')['default']
    TestedHardware: typeof import('./src/components/TestedHardware.vue')['default']
  }
}
